name: jpingus-spawn
version: 1.0-SNAPSHOT
author: jPingus
main: lu.jpingus.minecraft.spawn.JpingusSpawnPlugin
api-version: 1.16
commands:
  spawn:
    description: "return to world spawn"
    usage: "Usage: /<command>"
    permission: jpingus.everybody
  bed:
    description: "return to your bed"
    usage: "Usage: /<command>"
    permission: jpingus.everybody

permissions:
  jpingus.everybody:
    description: "everybody"
    default: true